[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.pylint.master]
ignore-patterns = "test_.*?py"

[tool.pylint.basic]
good-names = "i,j,k,_,a,b,c,x,y,z,t,n,ax,f,T"

[tool.pylint.messages_control]
disable = "R,C0330,C0326,W0511,W1203"

[tool.pylint.format]
max-line-length = 79
